apiVersion: 1

datasources:
  - name: lux-mon
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: luxmon
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      organization: luxmon
      tlsSkipVerify: true
    secureJsonData:
      token: ${LUX_INFLUX_TOKEN}
