#!/bin/bash
# One-command installer for lux-mon on Debian/Ubuntu/Raspberry Pi OS.
# Installs and configures: MariaDB, Python venv, InfluxDB, Mosquitto, Grafana,
# collector + API systemd services.
#
# Usage:
#   LUX_INSTALL_DIR=/opt/lux-mon LUX_USER=pi \
#   LUX_MARIADB_PASSWORD='db-password' \
#   LUX_INFLUX_ADMIN_PASSWORD='influx-password' \
#   bash scripts/install.sh
#
# Defaults:
#   LUX_INSTALL_DIR = /opt/lux-mon
#   LUX_USER        = current user
#   LUX_MARIADB_PASSWORD = luxmon
#   LUX_INFLUX_ADMIN_PASSWORD = required for InfluxDB bootstrap (no default)

set -e

LUX_INSTALL_DIR="${LUX_INSTALL_DIR:-/opt/lux-mon}"
LUX_USER="${LUX_USER:-$(whoami)}"
LUX_MARIADB_PASSWORD="${LUX_MARIADB_PASSWORD:-luxmon}"
LUX_DONGLE_HOST="${LUX_DONGLE_HOST:-192.168.1.100}"
LUX_DONGLE_PORT="${LUX_DONGLE_PORT:-8000}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

if [[ "$EUID" -eq 0 ]]; then
  SUDO=""
else
  SUDO="sudo"
fi

echo "==> lux-mon installer"
echo "    install dir: $LUX_INSTALL_DIR"
echo "    run user:    $LUX_USER"

# ── System packages ────────────────────────────────────────────────────
echo "==> Updating package lists..."
$SUDO apt-get update

echo "==> Installing system dependencies..."
$SUDO apt-get install -y \
  git \
  curl \
  rsync \
  python3 \
  python3-venv \
  python3-pip \
  python3-dev \
  pkg-config \
  build-essential \
  default-libmysqlclient-dev \
  mariadb-server \
  mariadb-client \
  libssl-dev

# ── MariaDB ──────────────────────────────────────────────────────────────
echo "==> Configuring MariaDB..."
$SUDO systemctl enable mariadb || true
$SUDO systemctl start mariadb || true

# Create database + user if they don't exist
$SUDO mariadb -u root <<EOF
CREATE DATABASE IF NOT EXISTS luxmon CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'luxmon'@'localhost' IDENTIFIED BY '${LUX_MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON luxmon.* TO 'luxmon'@'localhost';
FLUSH PRIVILEGES;
EOF

# ── Install code ────────────────────────────────────────────────────────
echo "==> Installing lux-mon to $LUX_INSTALL_DIR..."
if [[ ! -d "$LUX_INSTALL_DIR" ]]; then
  $SUDO mkdir -p "$LUX_INSTALL_DIR"
  $SUDO chown "$LUX_USER:$LUX_USER" "$LUX_INSTALL_DIR"
fi

if [[ -d "$REPO_DIR/.git" ]]; then
  echo "    copying from local repo: $REPO_DIR"
  rsync -avz --delete \
    --exclude='.git' --exclude='venv' --exclude='__pycache__' --exclude='*.pyc' --exclude='.env' \
    "$REPO_DIR/" "$LUX_INSTALL_DIR/"
else
  echo "    cloning from GitHub..."
  git clone https://github.com/jmewing/lux-mon.git "$LUX_INSTALL_DIR"
fi

# ── Python venv ──────────────────────────────────────────────────────────
echo "==> Creating Python virtual environment..."
cd "$LUX_INSTALL_DIR"
python3 -m venv venv
venv/bin/pip install --upgrade pip
venv/bin/pip install -r docker/requirements.txt

# ── Add lux-mon user to dialout group for RS-485 serial access ───────────
echo "==> Granting serial port access to ${LUX_USER}..."
$SUDO usermod -aG dialout ${LUX_USER} || true

# ── Make CLI entrypoints executable ──────────────────────────────────────
echo "==> Installing lux-mon CLI entrypoints..."
$SUDO chmod +x "${LUX_INSTALL_DIR}/bin/latest_snapshot.py"
$SUDO chmod +x "${LUX_INSTALL_DIR}/bin/lux-mon-rs485"
if [[ -d /usr/local/bin ]]; then
  $SUDO ln -sf "${LUX_INSTALL_DIR}/bin/lux-mon-rs485" /usr/local/bin/lux-mon-rs485 || true
  $SUDO ln -sf "${LUX_INSTALL_DIR}/scripts/discover-rs485.py" /usr/local/bin/lux-mon-discover-rs485 || true
fi

# ── InfluxDB + Mosquitto + Grafana ────────────────────────────────────────
echo "==> Installing InfluxDB + Mosquitto + Grafana..."
LUX_INFLUX_ADMIN_PASSWORD="${LUX_INFLUX_ADMIN_PASSWORD:-}" bash "$LUX_INSTALL_DIR/scripts/setup-grafana-stack.sh"

# ── .env file ────────────────────────────────────────────────────────────
if [[ ! -f "$LUX_INSTALL_DIR/.env" ]]; then
  echo "==> Creating $LUX_INSTALL_DIR/.env..."

  INFLUX_TOKEN=""
  if [[ -f /tmp/influx-luxmon.token ]]; then
    INFLUX_TOKEN=$(cat /tmp/influx-luxmon.token)
  fi

  cat > "$LUX_INSTALL_DIR/.env" <<EOF
# Generated by scripts/install.sh on $(date -Iseconds)

# Transport
LUX_TRANSPORT=tcp_active
LUX_DONGLE_HOST=${LUX_DONGLE_HOST}
LUX_DONGLE_PORT=${LUX_DONGLE_PORT}
LUX_POLL_INTERVAL=2.0

# MariaDB
LUX_MARIADB_ENABLED=true
LUX_MARIADB_HOST=localhost
LUX_MARIADB_PORT=3306
LUX_MARIADB_USER=luxmon
LUX_MARIADB_PASSWORD=${LUX_MARIADB_PASSWORD}
LUX_MARIADB_DATABASE=luxmon
LUX_MARIADB_TABLE_PREFIX=lux_

# InfluxDB
LUX_INFLUX_ENABLED=true
LUX_INFLUX_URL=http://localhost:8086
LUX_INFLUX_ORG=luxmon
LUX_INFLUX_BUCKET=luxmon
LUX_INFLUX_TOKEN=${INFLUX_TOKEN}

# MQTT
LUX_MQTT_ENABLED=true
LUX_MQTT_HOST=localhost
LUX_MQTT_PORT=1883
LUX_MQTT_TOPIC_PREFIX=luxmon
LUX_MQTT_HA_DISCOVERY=true
LUX_MQTT_HA_PREFIX=homeassistant
LUX_MQTT_DEVICE_NAME=luxmon
LUX_MQTT_DEVICE_ID=luxmon_solar
EOF
  chmod 600 "$LUX_INSTALL_DIR/.env"
else
  echo "==> .env already exists, preserving it"
fi

# ── systemd services ─────────────────────────────────────────────────────
echo "==> Installing systemd services..."
$SUDO tee /etc/systemd/system/lux-mon.service >/dev/null <<EOF
[Unit]
Description=lux-mon collector
After=network.target mariadb.service influxdb.service mosquitto.service
Wants=mariadb.service influxdb.service mosquitto.service

[Service]
Type=simple
User=${LUX_USER}
WorkingDirectory=${LUX_INSTALL_DIR}
ExecStart=${LUX_INSTALL_DIR}/venv/bin/python3 -m collector
Restart=always
RestartSec=5
EnvironmentFile=-${LUX_INSTALL_DIR}/.env

[Install]
WantedBy=multi-user.target
EOF

$SUDO tee /etc/systemd/system/lux-api.service >/dev/null <<EOF
[Unit]
Description=lux-mon REST API server
After=network.target mariadb.service
Wants=mariadb.service

[Service]
Type=simple
User=${LUX_USER}
WorkingDirectory=${LUX_INSTALL_DIR}
ExecStart=${LUX_INSTALL_DIR}/venv/bin/python3 -m api
Restart=always
RestartSec=5
Environment=LUX_API_HOST=0.0.0.0
Environment=LUX_API_PORT=8080
EnvironmentFile=-${LUX_INSTALL_DIR}/.env

[Install]
WantedBy=multi-user.target
EOF

# ── Initialize DB tables ─────────────────────────────────────────────────
echo "==> Initializing database tables..."
cd "$LUX_INSTALL_DIR"
LUX_MARIADB_PASSWORD="$LUX_MARIADB_PASSWORD" venv/bin/python3 - <<'PYEOF'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from collector.outputs import Outputs, OutputConfig

c = OutputConfig(
    mariadb_enabled=True,
    mariadb_host=os.environ.get('LUX_MARIADB_HOST', 'localhost'),
    mariadb_port=int(os.environ.get('LUX_MARIADB_PORT', '3306')),
    mariadb_user=os.environ.get('LUX_MARIADB_USER', 'luxmon'),
    mariadb_password=os.environ.get('LUX_MARIADB_PASSWORD', 'luxmon'),
    mariadb_database=os.environ.get('LUX_MARIADB_DATABASE', 'luxmon'),
    mariadb_table_prefix=os.environ.get('LUX_MARIADB_TABLE_PREFIX', 'lux_'),
    influx_enabled=False,
    mqtt_enabled=False,
)

o = Outputs(c)
o._init_mariadb()
print("MariaDB tables initialized")
PYEOF

# ── Start services ───────────────────────────────────────────────────────
echo "==> Enabling and starting services..."
$SUDO systemctl daemon-reload
$SUDO systemctl enable lux-mon.service lux-api.service
$SUDO systemctl restart lux-mon.service lux-api.service

# ── Optional RS-485 collector service ────────────────────────────────────
if [[ "${LUX_RS485_ENABLED:-}" == "true" ]]; then
  echo "==> Installing RS-485 collector service..."
  $SUDO tee /etc/systemd/system/lux-mon-rs485.service >/dev/null <<EOF
[Unit]
Description=lux-mon RS-485 serial collector
After=network.target mariadb.service mosquitto.service
Wants=mariadb.service

[Service]
Type=simple
User=${LUX_USER}
Group=dialout
WorkingDirectory=${LUX_INSTALL_DIR}
ExecStart=${LUX_INSTALL_DIR}/bin/lux-mon-rs485
Restart=always
RestartSec=5
EnvironmentFile=-${LUX_INSTALL_DIR}/.env

[Install]
WantedBy=multi-user.target
EOF
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable lux-mon-rs485.service
  $SUDO systemctl restart lux-mon-rs485.service || true
fi

sleep 3
$SUDO systemctl status lux-mon.service --no-pager || true
$SUDO systemctl status lux-api.service --no-pager || true
if [[ "${LUX_RS485_ENABLED:-}" == "true" ]]; then
  $SUDO systemctl status lux-mon-rs485.service --no-pager || true
fi

# ── Grafana reverse proxy hint ──────────────────────────────────────────
echo ""
echo "==> lux-mon installed."
echo "    Dashboard: http://<this-host>/   (via Apache/Nginx reverse proxy to port 8080)"
echo "    API:       http://<this-host>:8080/api/status"
echo "    Grafana:   http://<this-host>:3000/grafana/d/lux-mon-charts/lux-mon-charts"
echo ""
echo "Next steps:"
echo "  1. Update serial numbers in $LUX_INSTALL_DIR/.env or via the web UI."
echo "  2. Point your dongle IP to $LUX_DONGLE_HOST if it differs from 192.168.1.100."
echo "  3. Add an Apache/Nginx reverse proxy for port 80 if desired."
